[functions.ask-card]
verify_jwt = true

[functions.create-game]
verify_jwt = true

[functions.get-game-state]
verify_jwt = true

[functions.heartbeat]
verify_jwt = true

[functions.join-game]
verify_jwt = true

[functions.join-random-game]
verify_jwt = true

[functions.randomize-teams]
verify_jwt = true

[functions.start-game]
verify_jwt = true

[functions.submit-claim]
verify_jwt = true

[functions.update-team-names]
verify_jwt = true

[auth]
enable_anonymous_sign_ins = false
password_requirements = "lower_upper_letters_digits_symbols"

[auth.email]
enable_signup = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
